apiVersion: 1

datasources:
  - name: Web3-sepolia-DB
    type: postgres
    uid: uid_sepolia_stable
    url: 127.0.0.1:5432
    database: web3_indexer
    user: postgres
    secureJsonData:
      password: uWNZugjBqixf8dxC
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 50
      maxIdleConns: 50
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false

  - name: Web3-demo-DB
    type: postgres
    uid: uid_demo_stable
    url: 127.0.0.1:5432
    database: web3_demo
    user: postgres
    secureJsonData:
      password: uWNZugjBqixf8dxC
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 50
      maxIdleConns: 50
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
