services:
  # Grafana
  grafana:
    image: grafana/grafana-oss:11.5.0
    container_name: web3-indexer-grafana
    deploy:
      resources:
        limits:
          memory: 256M
    restart: always
    network_mode: host
    volumes:
      - ../grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=4000
      - GF_SECURITY_ADMIN_PASSWORD=uWNZugjBqixf8dxC
      - GF_SERVER_ROOT_URL=https://grafana-demo2.st6160.click/
      - GF_SERVER_DOMAIN=grafana-demo2.st6160.click
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: web3-indexer-prometheus
    deploy:
      resources:
        limits:
          memory: 256M
    restart: always
    network_mode: host
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.listen-address=:9091'
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
