global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'web3-indexer-demo'
    static_configs:
      - targets: ['web3-indexer-anvil-app:8080']
    metrics_path: /metrics

  - job_name: 'web3-indexer-sepolia'
    static_configs:
      - targets: ['web3-indexer-sepolia-app:8080']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']