# Last updated: 2026-02-15 21:05 (Explicit IPv4)
global:
  scrape_interval: 2s # 缩短抓取时间，实时反馈
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'web3-indexer-demo'
    static_configs:
      - targets: ['127.0.0.1:8081']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'host-b1'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9091']